### ISSUE TITLE
nfl game error

### ISSUE THREAD

**Issue by scl2b** [mSengera/NFL-Game-Predictor#1]
hello 

i'm trying to launch main.py with idle but i get this message : 

"nflgame requires Python 2.7 and does not yet work with Python 3
You are running Python version 3.7"

any help to use nflgame on python 3.7 ?

best regards

**Comment by mSengera** [comment]
Hey!
Please download the nflgame extension for Python 3.

You can find the Repo here: https://github.com/mlenzen/nflgame

You can simply overwrite the nflgame for Python 2 data with the data for python 3.

All will work than fine.
